# Generated by Django 3.2.5 on 2024-03-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiresponse',
            name='choice_type',
            field=models.CharField(default='single', max_length=100),
            preserve_default=False,
        ),
    ]
