# Generated by Django 3.2.5 on 2024-03-25 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0002_apiresponse_choice_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onboarding',
            name='timestamp',
        ),
    ]
