# Generated by Django 3.2.5 on 2024-02-11 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0003_alter_onboarding_birth_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='female', max_length=6),
            preserve_default=False,
        ),
    ]
