# Generated by Django 3.2.5 on 2024-02-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0004_onboarding_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default='2024-01-01 00:00'),
            preserve_default=False,
        ),
    ]
