# Generated by Django 3.2.5 on 2024-02-18 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0006_symptom'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='symptom_id',
            field=models.CharField(default='000000', max_length=100),
            preserve_default=False,
        ),
    ]
