# Generated by Django 3.2.5 on 2024-02-19 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0007_symptom_symptom_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptom',
            name='conversation_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
