# Generated by Django 3.2.5 on 2024-02-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0009_choice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
