# Generated by Django 3.2.5 on 2024-02-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0010_delete_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('choice_id', models.CharField(max_length=100)),
                ('conversation_id', models.CharField(max_length=100)),
            ],
        ),
    ]
