# Generated by Django 3.2.5 on 2024-02-26 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0011_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('condition_id', models.CharField(max_length=100)),
                ('conversation_id', models.CharField(max_length=100)),
            ],
        ),
    ]
