# Generated by Django 3.2.5 on 2024-03-01 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0012_condition'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Condition',
            new_name='MultipleChoice',
        ),
        migrations.RenameModel(
            old_name='Choice',
            new_name='SingleChoice',
        ),
        migrations.DeleteModel(
            name='Symptom',
        ),
        migrations.RenameField(
            model_name='multiplechoice',
            old_name='condition_id',
            new_name='choice_id',
        ),
    ]
