# Generated by Django 3.2.5 on 2024-03-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0013_auto_20240301_2223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=100)),
            ],
        ),
    ]
