# Generated by Django 3.2.5 on 2024-03-09 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0014_phase'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=100)),
                ('question_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Phase',
        ),
    ]
