# Generated by Django 3.2.5 on 2024-03-11 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0015_auto_20240309_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.CharField(max_length=1000)),
            ],
        ),
    ]
