# Generated by Django 3.2.5 on 2024-03-12 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0016_textinput'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TextInput',
        ),
    ]
