# Generated by Django 3.2.5 on 2024-03-16 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0018_textinput'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_name', models.CharField(max_length=1000)),
            ],
        ),
    ]
