# Generated by Django 3.2.5 on 2024-03-16 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0019_healthbackground'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthbackground',
            old_name='condition_name',
            new_name='condition_ID',
        ),
    ]
