# Generated by Django 3.2.5 on 2024-03-16 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0020_rename_condition_name_healthbackground_condition_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthbackground',
            old_name='condition_ID',
            new_name='condition_id',
        ),
    ]
