# Generated by Django 3.2.5 on 2024-03-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0021_rename_condition_id_healthbackground_condition_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationId',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.CharField(max_length=1000)),
            ],
        ),
    ]
