# Generated by Django 3.2.5 on 2024-03-17 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0022_conversationid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=1000)),
                ('language_code', models.CharField(max_length=10)),
            ],
        ),
    ]
