# Generated by Django 3.2.5 on 2024-03-19 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0023_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversationId',
        ),
        migrations.AddField(
            model_name='apiresponse',
            name='conversation_id',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiresponse',
            name='has_contraints',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apiresponse',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apiresponse',
            name='max_constraints',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apiresponse',
            name='message_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='apiresponse',
            name='min_constraints',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='apiresponse',
            name='multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='apiresponse',
            name='progress_percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiresponse',
            name='progress_stage',
            field=models.CharField(default='start', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiresponse',
            name='scenario',
            field=models.CharField(default='start', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='apiresponse',
            name='step_back_possible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='apiresponse',
            name='question_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
