# Generated by Django 3.2.5 on 2024-03-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0024_auto_20240320_1630'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiresponse',
            name='conversation_id',
        ),
        migrations.RemoveField(
            model_name='apiresponse',
            name='has_contraints',
        ),
        migrations.RemoveField(
            model_name='apiresponse',
            name='mandatory',
        ),
        migrations.RemoveField(
            model_name='apiresponse',
            name='max_constraints',
        ),
        migrations.RemoveField(
            model_name='apiresponse',
            name='message_type',
        ),
        migrations.RemoveField(
            model_name='apiresponse',
            name='min_constraints',
        ),
        migrations.RemoveField(
            model_name='apiresponse',
            name='multiple',
        ),
        migrations.RemoveField(
            model_name='apiresponse',
            name='progress_percentage',
        ),
        migrations.RemoveField(
            model_name='apiresponse',
            name='progress_stage',
        ),
        migrations.RemoveField(
            model_name='apiresponse',
            name='scenario',
        ),
        migrations.RemoveField(
            model_name='apiresponse',
            name='step_back_possible',
        ),
        migrations.AlterField(
            model_name='apiresponse',
            name='question_type',
            field=models.CharField(default='start', max_length=100),
            preserve_default=False,
        ),
    ]
