# Generated by Django 3.2.5 on 2024-03-19 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0024_auto_20240319_2124'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
