# Generated by Django 3.2.5 on 2024-03-19 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0025_delete_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiresponse',
            old_name='max_constraints',
            new_name='max_selection',
        ),
        migrations.RenameField(
            model_name='apiresponse',
            old_name='min_constraints',
            new_name='min_selection',
        ),
    ]
