# Generated by Django 3.2.5 on 2024-03-19 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0026_auto_20240319_2200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiresponse',
            name='message_type',
        ),
    ]
