# Generated by Django 3.2.5 on 2024-03-19 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0027_remove_apiresponse_message_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiresponse',
            old_name='has_contraints',
            new_name='has_constraints',
        ),
        migrations.AlterField(
            model_name='apiresponse',
            name='mandatory',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='apiresponse',
            name='multiple',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
