# Generated by Django 3.2.5 on 2024-03-19 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0028_auto_20240319_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiresponse',
            name='mandatory',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='apiresponse',
            name='multiple',
            field=models.BooleanField(null=True),
        ),
    ]
