# Generated by Django 3.2.5 on 2024-03-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0030_conversationid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiresponse',
            name='max_selection',
        ),
        migrations.RemoveField(
            model_name='apiresponse',
            name='min_selection',
        ),
    ]
