# Generated by Django 3.2.5 on 2024-03-20 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digidoc', '0031_auto_20240320_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiresponse',
            name='conversation_id',
        ),
    ]
